### ISSUE TITLE
USB connection

### ISSUE THREAD

**Issue by doragasu** [wuxx/nanoCH32V003#2]
Looks like `USB_N` and `USB_P` are not connected to the MCU. Could you confirm? Also could you connect them to the MCU for the next release of the PCB? This could allow using things like [rv003usb](https://github.com/cnlohr/rv003usb/).

**Comment by wuxx** [comment]
Hello, in fact, CH32V003 does not have hardware USB, the next version may pull out the signal line by this software USB implemented

**Comment by doragasu** [comment]
Thanks for the confirmation, and for considering the software USB option for the next version.
